### ISSUE TITLE
Script updates

### ISSUE THREAD

**Issue by bartosjiri** [UserOfficeProject/user-office-develop#7]
Hey all,

are there any plans to update the script, as it is currently referencing files that don't even exist on default branches of individual repositories (namely some `docker-compose.dev.yml`)?

Thanks!

**Comment by peter-asztalos** [comment]
Hey,

Sorry, I think this repo should be deprecated now, anyway, you can get started with User Office with user-office-backend, the docker-compose file there should get you everything except the backend and frontend, those you have to run manually (npm run dev in both repo). 
Please also check the example.env

**Comment by bartosjiri** [comment]
Sounds good, thanks for the prompt response!
